[tool.poetry]
name = "img2tags"
version = "1.3.4"
description = "Tag images"
authors = ["Yuta Hayashibe <yuta@hayashibe.jp>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/shirayu/img2tags"
repository = "https://github.com/shirayu/img2tags"
packages = [{include = "img2tags"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
opencv-python = "^4.7.0.72"
numpy = "^1.24.3"
torch = ">=2.1.0"
huggingface-hub = "^0.15.1"
tqdm = "^4.65.0"
pillow = "^9.5.0"
onnxruntime = { version = "^1.16.1", optional = true }
onnxruntime-gpu = { version = "^1.16.1", optional = true }
onnx = {version="^1.14.0", optional = true }
pydantic = "^1.10.9"

[tool.poetry.extras]
convert = ["onnx"]
cpu = ["onnxruntime"]
gpu = ["onnxruntime-gpu"]

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
isort = "^5.12.0"
toml = "^0.10.2"
flake8 = ">=5.0.4"
pydocstyle = ">=6.1.1"
pytest = "^7.2.1"
yamllint = "^1.32.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
img2tags = "img2tags.cli:main"

[tool.pyright]
pythonVersion = "3.9"
typeCheckingMode = "basic"
exclude = [".venv", "**/node_modules", "**/__pycache__",]
reportPrivateImportUsage = "information"
reportUnusedVariable="warning"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
